
import React from 'react';

// This logo was conceptually designed as if generated by NanoBanana AI.
// It represents a modern, sleek shield symbolizing protection and trust.
const Logo: React.FC<{ className?: string }> = ({ className }) => {
    return (
        <svg
            className={className}
            viewBox="0 0 24 24"
            fill="none"
            xmlns="http://www.w3.org/2000/svg"
            aria-label="GuardPlus Logo"
        >
            <path
                d="M12 2L3 5V11C3 16.52 7.08 21.61 12 23C16.92 21.61 21 16.52 21 11V5L12 2Z"
                stroke="currentColor"
                strokeWidth="2"
                strokeLinecap="round"
                strokeLinejoin="round"
            />
            <path
                d="M12 11L15 8L12 5L9 8L12 11Z"
                fill="currentColor"
            />
        </svg>
    );
};

export default Logo;
