
import React from 'react';
import { ARTICLES, COUPANG_LINK } from '../../constants';
import { useSeo } from '../../hooks/useSeo';
import CTAButton from '../ui/CTAButton';

interface ArticlePageProps {
    slug: string;
}

const ArticlePage: React.FC<ArticlePageProps> = ({ slug }) => {
    const article = ARTICLES.find((a) => a.slug === slug);

    useSeo({
        title: article ? `${article.title} | 가드플러스` : '가드를 올리다',
        description: article ? article.description : '',
        keywords: article ? article.keywords : '',
        ogImage: article ? article.image : '',
    });

    if (!article) {
        return (
            <div className="text-center py-20">
                <h1 className="text-3xl font-bold">404 - 페이지를 찾을 수 없습니다.</h1>
                <p className="mt-4">요청하신 아티클을 찾을 수 없습니다.</p>
                <div className="mt-8">
                    <a href="#/" className="text-blue-600 hover:underline">홈으로 돌아가기</a>
                </div>
            </div>
        );
    }
    
    const otherArticles = ARTICLES.filter(a => a.slug !== slug).slice(0, 2);

    return (
        <article className="max-w-4xl mx-auto fade-in">
            {/* Breadcrumbs */}
            <nav className="mb-6 text-sm text-gray-500 dark:text-gray-400">
                <a href="#/" className="hover:underline">홈</a>
                <span className="mx-2">&gt;</span>
                <a href="#/articles" className="hover:underline">전체 가이드</a>
                <span className="mx-2">&gt;</span>
                <span className="text-gray-700 dark:text-gray-200">{article.title}</span>
            </nav>

            <header>
                <h1 className="text-3xl md:text-5xl font-extrabold text-gray-900 dark:text-white leading-tight">
                    {article.title}
                </h1>
                <p className="mt-4 text-lg text-gray-600 dark:text-gray-300">{article.description}</p>
                <p className="mt-4 text-sm text-gray-500 dark:text-gray-400">
                    게시일: {article.publishedDate}
                </p>
            </header>
            
            <div className="my-8">
                 {/* Concept image generated by NanoBanana AI: A dramatic lifestyle shot related to the article's content. */}
                <img src={article.image} alt={article.title} className="w-full h-auto rounded-lg shadow-lg object-cover" style={{maxHeight: '500px'}}/>
            </div>

            <div className="prose prose-lg dark:prose-invert max-w-none">
                {article.content()}
            </div>
            
            <hr className="my-12 border-gray-200 dark:border-gray-700" />
            
            {/* CTA Section */}
            <section className="text-center bg-gray-100 dark:bg-gray-800 p-8 rounded-lg">
                <h2 className="text-2xl font-bold">더 늦기 전에, 당신의 안전을 준비하세요</h2>
                <p className="mt-2 text-gray-600 dark:text-gray-300">지금 바로 가드플러스로 예측 불가능한 위험에 대비하세요.</p>
                <div className="mt-6">
                    <CTAButton link={COUPANG_LINK} text="쿠팡에서 최저가로 구매하기" isPrimary={true} />
                </div>
            </section>
            
            {/* Internal Links Section */}
            <section className="mt-12">
                <h3 className="text-2xl font-bold mb-4">함께 읽어보면 좋은 글</h3>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                    {otherArticles.map(other => (
                        <a key={other.slug} href={`#/articles/${other.slug}`} className="p-4 border rounded-lg hover:bg-gray-50 dark:hover:bg-gray-800 transition-colors">
                            <h4 className="font-semibold text-lg text-blue-600 dark:text-blue-400">{other.title}</h4>
                            <p className="mt-1 text-sm text-gray-600 dark:text-gray-400">{other.description}</p>
                        </a>
                    ))}
                </div>
            </section>
        </article>
    );
};

export default ArticlePage;
