
import React from 'react';
import CTAButton from '../ui/CTAButton';
import { useSeo } from '../../hooks/useSeo';
import { ARTICLES, COUPANG_LINK } from '../../constants';
import ArticleCard from '../ui/ArticleCard';

const HomePage: React.FC = () => {
    useSeo({
        title: '가드플러스 호신용 스프레이 | 공식 리뷰 및 구매 가이드',
        description: '가드플러스 호신용 스프레이의 모든 것. 실사용 후기, 법적 규제, 안전 사용법, 그리고 최저가 구매 정보까지 확인하세요. 당신의 안전을 위한 최고의 선택.',
        keywords: '가드플러스, 호신용 스프레이, pepper spray, self defense spray, 여성 호신, 야간 안전, 범죄 예방',
        ogImage: 'https://picsum.photos/1200/630?random=1'
    });
    
    const featuredArticles = ARTICLES.slice(0, 3);

    return (
        <div className="space-y-16 md:space-y-24 fade-in">
            {/* Hero Section */}
            <section className="text-center pt-8">
                <h1 className="text-4xl md:text-6xl font-extrabold tracking-tight text-gray-900 dark:text-white">
                    <span className="text-blue-600 dark:text-blue-500">가장 확실한 안전,</span>
                    <br />
                    가드플러스 호신용 스프레이
                </h1>
                <p className="mt-4 max-w-2xl mx-auto text-lg md:text-xl text-gray-600 dark:text-gray-300">
                    예측 불가능한 위험으로부터 나를 지키는 가장 스마트한 방법. 강력한 성능과 뛰어난 휴대성으로 당신의 일상에 안심을 더하세요.
                </p>
                <div className="mt-8 flex justify-center gap-4">
                    <CTAButton link={COUPANG_LINK} text="쿠팡에서 최저가로 구매하기" isPrimary={true} />
                    <CTAButton link="#/articles" text="핵심 가이드 바로가기" />
                </div>
                <div className="mt-12">
                    {/* Concept image generated by NanoBanana AI: A high-resolution shot of the GuardPlus spray on a clean, white background. */}
                    <img src="https://picsum.photos/800/500?random=6" alt="가드플러스 호신용 스프레이 제품" className="mx-auto rounded-lg shadow-2xl" />
                </div>
            </section>

            {/* Features Section */}
            <section>
                <div className="grid grid-cols-1 md:grid-cols-3 gap-8 text-center">
                    <div className="p-6">
                        <div className="flex justify-center items-center h-12 w-12 rounded-md bg-blue-500 text-white mx-auto">
                            <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M13 10V3L4 14h7v7l9-11h-7z" /></svg>
                        </div>
                        <h3 className="mt-5 text-xl font-semibold">강력한 분사력</h3>
                        <p className="mt-2 text-gray-600 dark:text-gray-400">최대 5m의 유효 사거리로 안전거리를 확보하며 위협에 즉각 대응할 수 있습니다.</p>
                    </div>
                    <div className="p-6">
                        <div className="flex justify-center items-center h-12 w-12 rounded-md bg-blue-500 text-white mx-auto">
                           <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 11c0 3.517-1.009 6.789-2.756 9.352A17.962 17.962 0 0112 21c3.517 0 6.789-1.009 9.352-2.756C19.604 15.68 18 12.41 18 9c0-3.866-3.134-7-7-7-1.094 0-2.12.253-3.037.697" /></svg>
                        </div>
                        <h3 className="mt-5 text-xl font-semibold">고농축 OC 성분</h3>
                        <p className="mt-2 text-gray-600 dark:text-gray-400">눈, 코, 피부에 즉각적인 효과를 발휘하여 상대방을 신속하게 무력화시킵니다.</p>
                    </div>
                    <div className="p-6">
                        <div className="flex justify-center items-center h-12 w-12 rounded-md bg-blue-500 text-white mx-auto">
                           <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M21 12a9 9 0 01-9 9m9-9a9 9 0 00-9-9m9 9H3m9 9a9 9 0 01-9-9m9 9V3m-9 9h18" /></svg>
                        </div>
                        <h3 className="mt-5 text-xl font-semibold">뛰어난 휴대성</h3>
                        <p className="mt-2 text-gray-600 dark:text-gray-400">컴팩트한 사이즈와 가벼운 무게로 언제 어디서든 부담 없이 휴대할 수 있습니다.</p>
                    </div>
                </div>
            </section>
            
            {/* Featured Articles Section */}
            <section>
                <div className="text-center mb-12">
                    <h2 className="text-3xl font-bold tracking-tight">필수 안전 가이드</h2>
                    <p className="mt-2 max-w-2xl mx-auto text-lg text-gray-600 dark:text-gray-300">
                        가드플러스를 100% 활용하기 위해 꼭 알아야 할 정보들을 확인하세요.
                    </p>
                </div>
                <div className="grid gap-8 md:grid-cols-2 lg:grid-cols-3">
                    {featuredArticles.map((article) => (
                        <ArticleCard key={article.slug} article={article} />
                    ))}
                </div>
            </section>
        </div>
    );
};

export default HomePage;
